replicaCount: 2

image:
  repository: traefik/whoami
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-whoami-prefix@kubernetescrd
  hosts:
    - host: ""
      paths:
        - path: /whoami
          pathType: Prefix
  tls: []
